package com.isep.hpah.core;

public enum Core {
    AFRICAN_MERMAID_HAIR,
    BASILISK_HORN,
    BONE,
    CURUPIRA_HAIR,
    DITTANY,
    DRAGON_HEARTSTRING,
    FAIRY_WINGS,
    HORNED_SERPENT_HORN,
    JACKALOPE_ANTLER,
    KELPIE_HAIR,
    KORALLE,
    PHOENIX_FEATHER,
    ROUGAROU_HAIR,
    SHELL,
    SNALLYGASTER_HEARTSTRING,
    SUPREME_CORES,
    THESTRAL_TAIL_HAIR,
    THUNDERBIRD_TAIL_FEATHER,
    TROLL_WHISKER,
    TWIN_WAND_CORES,
    UNICORN_HAIR,
    VEELA_HAIR,
    WAMPUS_CAT_HAIR,
    WAND_CORE,
    WHITE_RIVER_MONSTER_SPINE
}
